services:
  app:
    build: .
    container_name: devsecops-api

    ports:
      - "3000:3000"

    environment:
      MONGO_URI: mongodb://mongodb:27017/devsecops

    depends_on:
      - mongodb

  mongodb:
    image: mongo:8

    container_name: mongodb

    ports:
      - "27017:27017"

    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: