name: Node.js CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Semgrep
        run: |
              python3 -m pip install semgrep
      - name: Run Semgrep Scan   
        run: |
            semgrep scan \
            --config .semgrep/rules.yml \
            --error

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
         args: --severity-threshold=high

      - name: Run Tests
        run: npm test